name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  generate-snk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: omevi2079
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add changes
        run: |
          git add ./output/*.svg

      - name: Commit changes
        run: |
          git commit -m "chore: generate Pac-Man contribution graph" || echo "No changes to commit"

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/omevi2079/omevi2079.git
          git push origin HEAD:main
